birthday = input("What's your birthday? ")
print(f"{birthday} is a nice birthday!")
birthday2 = input("What's your birthday?")
print(f"{birthday2} is a nice birthday!")
birthday3 = input("What's your birthday? ")
print(f"{birthday3} is a nice birthday!")
birthday4 = input("What's your birthday?")
print(f"{birthday4} is a nice birthday!")
birthday5 = input("What's your birthday?")
print(f"{birthday5} is a nice birthday!")